const iconURL ='/icon';

const shortcutsInfo = {
    portal:[
        {
            id:"google",
            name:"구글",
            url:`${iconURL}/google.png`,
            type:"portal",
        },
        {
            id:"naver",
            name:"네이버",
            url:`${iconURL}/naver.png`,
            type:"portal",
        },
    ],
    sns:[
        {
            id:"facebook",
            name:"페이스북",
            url:`${iconURL}/facebook.png`,
            type:"sns",
        },
        {
            id:"instagram",
            name:"인스타그램",
            url:`${iconURL}/instagram.png`,
            type:"sns",
        },
        {
            id:"kakao_story",
            name:"카카오스토리",
            url:`${iconURL}/kakao_story.png`,
            type:"sns",
        },
        {
            id:"naver_band",
            name:"밴드",
            url:`${iconURL}/naver_band.png`,
            type:"sns",
        },
        {
            id:"twitter",
            name:"트위터",
            url:`${iconURL}/twitter.png`,
            type:"sns",
        },
    ],
    streaming:[
        {
            id:"youtube",
            name:"유튜브",
            url:`${iconURL}/youtube.png`,
            type:"streaming",
        },
        {
            id:"netflix",
            name:"넷플릭스",
            url:`${iconURL}/netflix.png`,
            type:"streaming",
        },
        {
            id:"watcha",
            name:"왓챠",
            url:`${iconURL}/watcha.png`,
            type:"streaming",
        },
    ],
    blog:[
        {
            id:"naver_blog",
            name:"네이버블로그",
            url:`${iconURL}/naver_blog.png`,
            type:"blog",
        },
        {
            id:"tistory",
            name:"티스토리",
            url:`${iconURL}/tistory.png`,
            type:"blog",
        },
    ],
    mylog:[],
};

export default shortcutsInfo;